{% set version = "1.4-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-polynom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/polynom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/polynom/polynom_{{ version }}.tar.gz
  sha256: bc1edb7bb16c8b299103f80a52ab8c5fc200cd07a9056578c1f672e9f5019278

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('polynom')"           # [not win]
    - "\"%R%\" -e \"library('polynom')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=polynom
  license: GPL-2.0-only
  summary: A collection of functions to implement a class for univariate polynomial manipulations.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: polynom
# Version: 1.4-0
# Title: A Collection of Functions to Implement a Class for Univariate Polynomial Manipulations
# Authors@R: c(person("Bill", "Venables", role = c("aut", "cre"), email = "Bill.Venables@gmail.com", comment = "S original"), person("Kurt", "Hornik", role = "aut", email = "Kurt.Hornik@R-project.org", comment = "R port"), person("Martin", "Maechler", role = "aut", email = "maechler@stat.math.ethz.ch", comment = "R port"))
# Description: A collection of functions to implement a class for univariate polynomial manipulations.
# Imports: stats, graphics
# License: GPL-2
# NeedsCompilation: no
# Author: Bill Venables [aut, cre] (S original), Kurt Hornik [aut] (R port), Martin Maechler [aut] (R port)
# Maintainer: Bill Venables <Bill.Venables@gmail.com>
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# Packaged: 2019-03-20 22:46:48 UTC; ven037
# Repository: CRAN
# Date/Publication: 2019-03-22 09:50:06 UTC
